[package]
name = "temari-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "temari"
path = "src/main.rs"

[dependencies]
temari-core = { path = "../temari-core" }
temari-schedule = { path = "../temari-schedule" }
anyhow.workspace = true
clap.workspace = true
directories.workspace = true
serde.workspace = true
serde_json.workspace = true
shlex.workspace = true
tempfile.workspace = true
