[package]
name = "temari-schedule"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
directories.workspace = true
serde.workspace = true
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true
